<?php
/**
 * Created by PhpStorm.
 * User: intern
 * Date: 2017/11/29
 * Time: 上午9:50
 */
namespace app\common\lib\exception;

use Exception;//引用tp5封装好的类
use think\exception\Handle;

//封装异常处理类: APIHandleException类
class ApiHandleException extends Handle {

//   使用Handle里的render方法
     public function render(Exception $e)
     {
         //如果配置文件里'app_debug'=>'turn' 使用父类的异常处理类方法render()
         if (config('app_debug')) {
             return parent::render($e); // TODO: Change the autogenerated stub
         }


         $httpCode = 500;//变量

         //使$e 的类型和 APIException 的类型一致
         if ($e instanceof ApiException) {

              $httpCode = $e->httpCode;
         }

         return show(-1,$e->getMessage(),[],$httpCode);
     }
}